name: Python application

on: push
# on:
#   schedule:
#     - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Application
      run: |
        pip install -r requirements.txt
        python report.py --file data/2021_12_27_Daten.csv
