on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Create Report
    - run: |
          pip install -r requirements.txt
          python report.py
    # - uses: actions/checkout@v2
    # - name: Commit Report
    #   run: |
    #     git config --global user.name 'nimpla'
    #     git config --global user.email '9716355+nimpla@users.noreply.github.com'
    #     git commit -am "Update Data"
    #     git push
